## @file
# File templates/pr-gate-build-job.yml
#
# template file used to build supported packages.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  tool_chain_tag: ''
  vm_image: ''
  arch_list: ''
  extra_steps: []   # MU_CHANGE

# Build step
jobs:

- job: Build_${{ parameters.tool_chain_tag }}

  #Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_MDE_CPU:
        Build.Pkgs: 'MdePkg,UefiCpuPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_MDEMODULE_DEBUG:
        Build.Pkgs: 'MdeModulePkg'
        Build.Targets: 'DEBUG,NOOPT'
      TARGET_MDEMODULE_RELEASE:
        Build.Pkgs: 'MdeModulePkg'
        Build.Targets: 'RELEASE,NO-TARGET'
      TARGET_NETWORK:
        Build.Pkgs: 'NetworkPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET'
      TARGET_OTHER:
        Build.Pkgs: 'PcAtChipsetPkg,StandaloneMmPkg,BaseTools' # MU_CHANGE add BaseTools`
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET'
      TARGET_TEST:
        Build.Pkgs: 'UnitTestFrameworkPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_SECURITY:
        Build.Pkgs: 'SecurityPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET'

  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - ${{ parameters.extra_steps }}   # MU_CHANGE
  - template: pr-gate-steps.yml
    parameters:
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      build_archs: ${{ parameters.arch_list }}
