# @file
# Sign EFI images and generate the per-architecture test-data C files consumed by
# ImageValidationTestApp.
#
# Rerun this script whenever the input images or the desired signing topology change.
# Every generated file carries a header pointing back here, so this module docstring
# (and `--help`) is the only place the workflow is documented.
#
# Given one unsigned EFI image per architecture, this script:
#   1. Generates signer 1's four-certificate chain (root CA -> intermediate 1 CA ->
#      intermediate 2 CA -> leaf) plus signer 2 (a single self-signed signer) and a couple
#      of unrelated decoy certificates with openssl.
#   2. Signs each image with the leaf certificate, embedding the intermediate 2 +
#      intermediate 1 + root chain, and additionally with signer 2 for the multi-signed
#      image (appending a second WIN_CERTIFICATE that also embeds the unrelated decoy
#      certificates) using sbsign.
#   3. Computes the Authenticode SHA-256, SHA-384, and SHA-512 digests of each image,
#      matching the hashes that SecurityPkg's DxeImageVerificationLib (HashPeImage) computes.
#      Each digest is identical for the unsigned, signed, and multi-signed forms of the same
#      image.
#   4. Emits the per-architecture C files X64/TestData.c and Aarch64/TestData.c, each
#      containing that architecture's images, digests, signer 1's leaf / intermediate 1 /
#      intermediate 2 / root certificates, signer 2's certificate, and one unrelated
#      certificate.
#
# Inputs
# ------
#   --x64-image <path>      Unsigned X64 PE/COFF EFI image to sign.
#   --aarch64-image <path>  Unsigned AARCH64 PE/COFF EFI image to sign.
# See `--help` for the remaining options (--output-dir, --openssl, --sbsign, --workdir, --keep).
#
# Outputs
# -------
#   X64/TestData.c          X64 image bytes, digests, and certificates.
#   Aarch64/TestData.c      AARCH64 image bytes, digests, and certificates.
#
# Tool requirements
# -----------------
#   - python3
#   - openssl
#   - sbsign ( Linux-native, use WSL on Windows)
# openssl and sbsign must be on PATH unless overridden with --openssl / --sbsign.
#   Ubuntu/Debian: sudo apt update && sudo apt install -y python3 openssl sbsigntool
#
# Usage
# -----
# Run from this directory (SecurityPkg/Test/ShellTest/ImageValidationTestApp).
#
#   # Both architectures.
#   python3 GenTestData.py --x64-image X64/HelloWorld.efi --aarch64-image Aarch64/HelloWorld.efi
#
#   # A single architecture.
#   python3 GenTestData.py --x64-image X64/HelloWorld.efi
#   python3 GenTestData.py --aarch64-image Aarch64/HelloWorld.efi
#
#   # Windows: run through WSL because the signing tools are Linux-native.
#   wsl bash -lc "python3 GenTestData.py --x64-image X64/HelloWorld.efi --aarch64-image Aarch64/HelloWorld.efi"
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

import argparse
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import tempfile

FILE_HEADER = """\
/** @file
    Test data for the Image Verification unit test application.

    This file is GENERATED by GenTestData.py. Do not edit by hand; rerun the script against
    the desired binaries to regenerate it.

    Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include "TestData.h"
"""


def emit_array(symbol, description, data):
    """Render one byte array and its size symbol as C source text.

    The returned text contains a short comment block, a CONST UINT8 array, and
    a matching CONST UINTN size definition.
    """
    lines = []
    lines.append("")
    lines.append("//")
    lines.append(f"// {description}")
    lines.append("//")
    lines.append(f"CONST UINT8  {symbol}[] = {{")
    if len(data) == 0:
        # An empty array is not valid C; keep a single zero byte placeholder.
        data = b"\x00"
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("  " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append(f"CONST UINTN  {symbol}Size = sizeof ({symbol});")
    return "\n".join(lines) + "\n"


def read_file(path):
    """Read a file as bytes and return its contents."""
    with open(path, "rb") as handle:
        return handle.read()


def write_c_file(path, arrays):
    """Write a generated C file for the provided arrays.

    Each array entry is a tuple of (symbol, description, data). The file is
    emitted with CRLF line endings to match EDK2 source formatting.
    """
    body = FILE_HEADER
    for symbol, description, data in arrays:
        body += emit_array(symbol, description, data)

    # Normalize to CRLF line endings per EDK2 coding standards, then write in
    # binary mode so newlines are not translated again by the platform.
    body = body.replace("\r\n", "\n").replace("\n", "\r\n")

    output_dir = os.path.dirname(path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(path, "wb") as handle:
        handle.write(body.encode("ascii"))

    print(f"Wrote {path}")


def run(cmd):
    """Run a subprocess command and require a zero exit status."""
    subprocess.run(cmd, check=True)


def tool_path(name, override):
    """Resolve the path to a required external tool.

    An explicit override wins. Otherwise PATH is searched. The process exits
    with a descriptive error if the tool cannot be found.
    """
    path = override or shutil.which(name)
    if path is None:
        sys.exit(f"error: required tool '{name}' was not found on PATH; install it or pass --{name} PATH")
    return path


def generate_signer(openssl, workdir, stem, common_name):
    """Create a self-signed RSA test signer.

    Returns a tuple of (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    run([
        openssl, "req", "-x509", "-newkey", "rsa:2048", "-sha256",
        "-keyout", key_pem, "-out", cert_pem, "-days", "3650",
        "-nodes", "-subj", "/CN=" + common_name,
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def read_text(path):
    """Read a text file and return its contents as a string."""
    with open(path, "r") as handle:
        return handle.read()


def write_text(path, text):
    """Write the provided string to a text file."""
    with open(path, "w") as handle:
        handle.write(text)


def generate_root_ca(openssl, workdir, stem, common_name):
    """Create a self-signed RSA root CA certificate.

    Returns a tuple of (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    run([
        openssl, "req", "-x509", "-newkey", "rsa:2048", "-sha256",
        "-keyout", key_pem, "-out", cert_pem, "-days", "3650", "-nodes",
        "-subj", "/CN=" + common_name,
        "-addext", "basicConstraints=critical,CA:TRUE",
        "-addext", "keyUsage=critical,keyCertSign,cRLSign",
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def generate_signed_cert(openssl, workdir, stem, common_name, ca_key, ca_cert, is_ca):
    """Create an RSA certificate signed by the given CA.

    is_ca selects whether the new certificate is itself a CA (an intermediate)
    or a leaf code-signing certificate. Returns
    (key_pem_path, cert_pem_path, cert_der_bytes).
    """
    key_pem = os.path.join(workdir, stem + ".key.pem")
    csr_pem = os.path.join(workdir, stem + ".csr.pem")
    cert_pem = os.path.join(workdir, stem + ".cert.pem")
    cert_der = os.path.join(workdir, stem + ".cert.der")
    ext_file = os.path.join(workdir, stem + ".ext")

    if is_ca:
        write_text(ext_file,
                   "basicConstraints=critical,CA:TRUE\n"
                   "keyUsage=critical,keyCertSign,cRLSign\n")
    else:
        write_text(ext_file,
                   "basicConstraints=critical,CA:FALSE\n"
                   "keyUsage=critical,digitalSignature\n"
                   "extendedKeyUsage=codeSigning\n")

    run([
        openssl, "req", "-newkey", "rsa:2048", "-sha256", "-nodes",
        "-keyout", key_pem, "-out", csr_pem, "-subj", "/CN=" + common_name,
    ])
    run([
        openssl, "x509", "-req", "-in", csr_pem, "-sha256", "-days", "3650",
        "-CA", ca_cert, "-CAkey", ca_key, "-CAcreateserial",
        "-extfile", ext_file, "-out", cert_pem,
    ])
    run([openssl, "x509", "-in", cert_pem, "-outform", "DER", "-out", cert_der])
    return key_pem, cert_pem, read_file(cert_der)


def sbsign_image(sbsign, key_pem, cert_pem, in_path, out_path, addcert=None):
    """Append a WIN_CERTIFICATE signature to in_path, writing the result to out_path.

    If addcert is given (a PEM file of extra certificates), those certificates
    are embedded in the signature so a verifier can build the full chain.
    """
    cmd = [sbsign, "--key", key_pem, "--cert", cert_pem]
    if addcert is not None:
        cmd += ["--addcert", addcert]
    cmd += ["--output", out_path, in_path]
    run(cmd)


def authenticode_digest(data, hash_name):
    """Compute the Authenticode digest of a PE/COFF image with the named hash.

    hash_name is any algorithm accepted by hashlib.new (for example "sha256",
    "sha384", or "sha512"). This mirrors the hashing performed by SecurityPkg's
    DxeImageVerificationLib (HashPeImage): the optional-header checksum field and
    the Certificate Table data directory entry are skipped, the sections are
    hashed in PointerToRawData order, and the attribute certificate table at the
    end of the file is excluded. The digest is therefore identical for the
    unsigned, signed, and multi-signed forms of the same image.
    """
    if data[0:2] != b"MZ":
        raise ValueError("not a PE image (missing MZ header)")
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\x00\x00":
        raise ValueError("not a PE image (missing PE signature)")

    coff = pe + 4
    num_sections = struct.unpack_from("<H", data, coff + 2)[0]
    size_opt = struct.unpack_from("<H", data, coff + 16)[0]
    opt = coff + 20
    magic = struct.unpack_from("<H", data, opt)[0]
    if magic == 0x10B:        # PE32
        datadir = opt + 96
    elif magic == 0x20B:      # PE32+
        datadir = opt + 112
    else:
        raise ValueError(f"unknown optional header magic 0x{magic:04x}")

    checksum_off = opt + 64
    size_of_headers = struct.unpack_from("<I", data, opt + 60)[0]
    cert_dir = datadir + 4 * 8        # Certificate Table is data directory index 4
    cert_size = struct.unpack_from("<I", data, cert_dir + 4)[0]

    sha = hashlib.new(hash_name)
    sha.update(data[0:checksum_off])                 # start .. checksum field
    sha.update(data[checksum_off + 4:cert_dir])      # checksum .. cert table entry
    sha.update(data[cert_dir + 8:size_of_headers])   # cert table entry .. end of headers
    hashed = size_of_headers

    sections = []
    for i in range(num_sections):
        base = opt + size_opt + i * 40
        raw_size = struct.unpack_from("<I", data, base + 16)[0]
        raw_ptr = struct.unpack_from("<I", data, base + 20)[0]
        sections.append((raw_ptr, raw_size))
    for raw_ptr, raw_size in sorted(sections):
        if raw_size == 0:
            continue
        sha.update(data[raw_ptr:raw_ptr + raw_size])
        hashed += raw_size

    trailing_end = len(data) - cert_size
    if trailing_end > hashed:
        sha.update(data[hashed:trailing_end])

    return sha.digest()


def build_arch_file(output_dir, file_name, arch_label, image_path,
                    leaf_key, leaf_cert, chain_pem,
                    signer2_key, signer2_cert, signer2_addcert,
                    certs, sbsign, workdir):
    """Sign one architecture's image and emit its test-data C file.

    The signed image is signed by signer 1's leaf certificate with the intermediate 2 +
    intermediate 1 + root chain embedded; the multi-signed image additionally carries
    signer 2's signature, which embeds unrelated decoy certificates. The
    architecture-independent certificates are emitted alongside the images/digests so each
    arch file is fully self-contained; only one arch file is compiled per build, so there
    is no duplicate-definition conflict.

    The generated file is written beneath output_dir using the provided file
    name relative path.
    """
    unsigned = read_file(image_path)
    signed_path = os.path.join(workdir, arch_label + ".signed.efi")
    multi_path = os.path.join(workdir, arch_label + ".multi.efi")

    sbsign_image(sbsign, leaf_key, leaf_cert, image_path, signed_path, addcert=chain_pem)
    sbsign_image(sbsign, signer2_key, signer2_cert, signed_path, multi_path,
                 addcert=signer2_addcert)

    signed = read_file(signed_path)
    multi = read_file(multi_path)

    arrays = [
        ("mUnsignedImage", f"unsigned {arch_label} PE/COFF image", unsigned),
        (
            "mSignedImage",
            f"{arch_label} PE/COFF image signed by the leaf cert (chain embedded)",
            signed,
        ),
        (
            "mMultiSignedImage",
            f"{arch_label} PE/COFF image signed by the leaf cert and signer 2",
            multi,
        ),
        (
            "mUnsignedImageDigestSha256",
            "Authenticode SHA-256 digest of the unsigned image",
            authenticode_digest(unsigned, "sha256"),
        ),
        (
            "mUnsignedImageDigestSha384",
            "Authenticode SHA-384 digest of the unsigned image",
            authenticode_digest(unsigned, "sha384"),
        ),
        (
            "mUnsignedImageDigestSha512",
            "Authenticode SHA-512 digest of the unsigned image",
            authenticode_digest(unsigned, "sha512"),
        ),
        (
            "mSignedImageDigestSha256",
            "Authenticode SHA-256 digest of the signed image",
            authenticode_digest(signed, "sha256"),
        ),
        (
            "mSignedImageDigestSha384",
            "Authenticode SHA-384 digest of the signed image",
            authenticode_digest(signed, "sha384"),
        ),
        (
            "mSignedImageDigestSha512",
            "Authenticode SHA-512 digest of the signed image",
            authenticode_digest(signed, "sha512"),
        ),
        (
            "mMultiSignedImageDigestSha256",
            "Authenticode SHA-256 digest of the multi-signed image",
            authenticode_digest(multi, "sha256"),
        ),
        (
            "mMultiSignedImageDigestSha384",
            "Authenticode SHA-384 digest of the multi-signed image",
            authenticode_digest(multi, "sha384"),
        ),
        (
            "mMultiSignedImageDigestSha512",
            "Authenticode SHA-512 digest of the multi-signed image",
            authenticode_digest(multi, "sha512"),
        ),
    ]
    arrays += certs
    write_c_file(os.path.join(output_dir, file_name), arrays)


def main():
    """Parse arguments, generate signed image artifacts, and emit test data C files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    arch_files = {
        "X64": os.path.join("X64", "TestData.c"),
        "AArch64": os.path.join("Aarch64", "TestData.c"),
    }

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Sign unsigned EFI images, generate signed and multi-signed test variants,\n"
            "compute their Authenticode SHA-256 digests, and emit the per-architecture\n"
            "C files X64/TestData.c and/or Aarch64/TestData.c consumed by\n"
            "ImageValidationTestApp. Provide at least one of --x64-image / --aarch64-image."
        ),
        epilog=(
            "requirements:\n"
            "  Requires python3, openssl, and sbsign. openssl and sbsign must be on\n"
            "  PATH unless overridden with --openssl / --sbsign. sbsign ships with the\n"
            "  sbsigntool / sbsigntools package (Linux-native; use WSL on Windows).\n"
            "    Ubuntu/Debian: sudo apt install -y python3 openssl sbsigntool\n"
            "\n"
            "examples:\n"
            "  # Generate test data for both architectures.\n"
            "  python3 GenTestData.py --x64-image X64/HelloWorld.efi \\\n"
            "                         --aarch64-image Aarch64/HelloWorld.efi\n"
            "\n"
            "  # Generate test data for a single architecture.\n"
            "  python3 GenTestData.py --x64-image X64/HelloWorld.efi\n"
            "\n"
            "  # On Windows, run through WSL because the signing tools are Linux-native.\n"
            "  wsl bash -lc \"python3 GenTestData.py --x64-image X64/HelloWorld.efi\"\n"
        ),
    )
    parser.add_argument("--x64-image", help="Unsigned X64 PE/COFF EFI image to sign.")
    parser.add_argument("--aarch64-image", help="Unsigned AARCH64 PE/COFF EFI image to sign.")
    parser.add_argument("--output-dir", default=script_dir,
                        help="Directory to write the generated C files (default: this directory).")
    parser.add_argument("--openssl", help="Path to the openssl executable (default: search PATH).")
    parser.add_argument("--sbsign", help="Path to the sbsign executable (default: search PATH).")
    parser.add_argument("--workdir",
                        help=(
                            "Directory for intermediate keys / signed images "
                            "(default: a temporary directory)."
                        ))
    parser.add_argument("--keep", action="store_true",
                        help=(
                            "Keep the intermediate artifacts instead of deleting "
                            "the temporary work directory."
                        ))
    args = parser.parse_args()

    images = []
    if args.x64_image:
        images.append(("X64", args.x64_image))
    if args.aarch64_image:
        images.append(("AArch64", args.aarch64_image))
    if not images:
        sys.exit("error: provide at least one of --x64-image / --aarch64-image")

    openssl = tool_path("openssl", args.openssl)
    sbsign = tool_path("sbsign", args.sbsign)

    created_workdir = args.workdir is None
    workdir = args.workdir or tempfile.mkdtemp(prefix="gentestdata_")
    os.makedirs(workdir, exist_ok=True)

    try:
        #
        # Build signer 1's four-certificate chain
        # (root CA -> intermediate 1 CA -> intermediate 2 CA -> leaf) used to sign the
        # images, plus signer 2 (a single self-signed signer) and unrelated decoy
        # certificates used for multi-signing.
        #
        root_key, root_cert, root_der = generate_root_ca(
            openssl, workdir, "root", "ImageVerificationTestApp Test Root CA"
        )
        int1_key, int1_cert, int1_der = generate_signed_cert(
            openssl, workdir, "intermediate1",
            "ImageVerificationTestApp Test Intermediate 1 CA",
            root_key, root_cert, is_ca=True
        )
        int2_key, int2_cert, int2_der = generate_signed_cert(
            openssl, workdir, "intermediate2",
            "ImageVerificationTestApp Test Intermediate 2 CA",
            int1_key, int1_cert, is_ca=True
        )
        leaf_key, leaf_cert, leaf_der = generate_signed_cert(
            openssl, workdir, "leaf",
            "ImageVerificationTestApp Test Leaf Signer",
            int2_key, int2_cert, is_ca=False
        )
        signer2_key, signer2_cert, signer2_der = generate_signer(
            openssl, workdir, "signer2", "ImageVerificationTestApp Test Signer 2"
        )

        #
        # Unrelated decoy certificates embedded in signer 2's signature. They are not part
        # of signer 2's (single-certificate) chain; they let tests confirm an image is not
        # authorized by an irrelevant certificate that merely rides along in the signature.
        # decoy 1 is exported as mSigner2UnrelatedCert for that purpose.
        #
        decoy1_key, decoy1_cert, decoy1_der = generate_signer(
            openssl, workdir, "decoy1", "ImageVerificationTestApp Test Unrelated Cert 1"
        )
        decoy2_key, decoy2_cert, decoy2_der = generate_signer(
            openssl, workdir, "decoy2", "ImageVerificationTestApp Test Unrelated Cert 2"
        )

        #
        # Chain PEM (intermediate 2 + intermediate 1 + root) embedded in the leaf signature
        # so a verifier can build leaf -> intermediate 2 -> intermediate 1 -> root and match
        # any of them enrolled in db / dbx.
        #
        chain_pem = os.path.join(workdir, "chain.pem")
        write_text(chain_pem,
                   read_text(int2_cert) + read_text(int1_cert) + read_text(root_cert))

        #
        # Decoy PEM embedded in signer 2's signature (unrelated to signer 2's chain).
        #
        signer2_addcert = os.path.join(workdir, "signer2_decoys.pem")
        write_text(signer2_addcert, read_text(decoy1_cert) + read_text(decoy2_cert))

        certs = [
            ("mLeafCert", "DER-encoded X.509 signer 1 leaf signing certificate", leaf_der),
            ("mIntermediate1Cert", "DER-encoded X.509 signer 1 intermediate 1 CA certificate", int1_der),
            ("mIntermediate2Cert", "DER-encoded X.509 signer 1 intermediate 2 CA certificate", int2_der),
            ("mRootCert", "DER-encoded X.509 signer 1 root CA certificate", root_der),
            ("mSigner2Cert", "DER-encoded X.509 certificate for signer 2", signer2_der),
            ("mSigner2UnrelatedCert",
             "DER-encoded X.509 certificate embedded in signer 2's signature but unrelated to its chain",
             decoy1_der),
        ]

        for arch_label, image_path in images:
            build_arch_file(args.output_dir, arch_files[arch_label], arch_label,
                            image_path, leaf_key, leaf_cert, chain_pem,
                            signer2_key, signer2_cert, signer2_addcert,
                            certs, sbsign, workdir)
    finally:
        if created_workdir and not args.keep:
            shutil.rmtree(workdir, ignore_errors=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
