/** @file
  Secure boot image validation test scenarios, registered as a single unit test suite.

  Each entry selects an image (IMAGE_TYPE_*) and the `db` / `dbx` contents to build
  (DB_STATE_* flags), then gives the EFI_STATUS that gBS->LoadImage() is expected to return.
  Refer to README.md ("Test Catalog") for the purpose, inputs, and expected result of every
  scenario, keyed by its test ID (the first TEST_SCENARIO argument).

  Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include "ImageValidationTestApp.h"

CONST SECURE_BOOT_IMAGE_TEST_SCENARIO  mScenarios[] = {
  TEST_SCENARIO (
    "1.1.1",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_EMPTY,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "1.2.1a",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "1.2.1b",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA384,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "1.2.1c",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA512,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "1.3.1a",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "1.3.1b",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "1.3.1c",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),

  TEST_SCENARIO (
    "2.1.1",
    IMAGE_TYPE_SIGNED,
    DB_STATE_EMPTY,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.1a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.1b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA384,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.1c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA512,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.2a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.2b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.2c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3e",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3f",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3g",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3h",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.2.3i",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.3.1a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.1b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.1c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.2a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.2b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.2c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.2d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3e",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3f",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3g",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3h",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3i",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3j",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3k",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA384,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.3.3l",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA512,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.1a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.1b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.1c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.1d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.2a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.2b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.2c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.2d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.3a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.3b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.3c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.3d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.4a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.4b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_CERT,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.4c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.4d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.5a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.5b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.5c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.5d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.6a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.6b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.6c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.6d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.7a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.7b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.7c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.7d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.8a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.8b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.8c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.8d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.9a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.9b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.9c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.9d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.10a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.10b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.10c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.10d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.11a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.11b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.11c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.11d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.12a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.12b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.12c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.12d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.13a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.13b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.13c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.13d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_ROOT_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.14a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.14b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.14c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.14d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.15a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.15b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.15c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.15d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.16a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.16b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.16c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.16d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "2.4.17a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT | DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.17b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT | DB_STATE_SIGNER1_INTERMEDIATE2_CERT,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.17c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256 | DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.4.17d",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256 | DB_STATE_SIGNER1_INTERMEDIATE2_TBS_HASH_SHA256,
    DB_STATE_SIGNER1_INTERMEDIATE1_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "2.5.1",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_SUCCESS
    ),

  TEST_SCENARIO (
    "3.1.1",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_EMPTY,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.1a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.1b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA384,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.1c",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA512,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.2",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.3a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_TBS_HASH_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.3b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_TBS_HASH_SHA384,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.2.3c",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_TBS_HASH_SHA512,
    DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.3.1",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "3.3.2",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "3.3.3",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "3.3.4",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_SIGNER2_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "3.3.5",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_EMPTY,
    DB_STATE_SIGNER1_LEAF_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.3.6",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_EMPTY,
    DB_STATE_SIGNER2_CERT,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "3.3.7",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_EMPTY,
    DB_STATE_SIGNER1_LEAF_CERT | DB_STATE_SIGNER2_CERT,
    EFI_ACCESS_DENIED
    ),

  TEST_SCENARIO (
    "4.1.1",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_UNRELATED_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "4.1.2a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "4.1.2b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA384,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "4.1.2c",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA512,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "4.2.1",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_SIGNER2_UNRELATED_CERT,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "4.2.2a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA256,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "4.2.2b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA384,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "4.2.2c",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_SIGNER2_UNRELATED_TBS_HASH_SHA512,
    EFI_SUCCESS
    ),

  TEST_SCENARIO (
    "5.1.1",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256 | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.1.2",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_CORRUPT_SIGNATURE_LIST_FIRST | DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.1.3",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.2.1a",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256 | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.2.1b",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.2.1c",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256 | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.2.2",
    IMAGE_TYPE_SIGNED,
    DB_STATE_CORRUPT_SIGNATURE_LIST_FIRST | DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.2.3",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.3.1a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.3.1b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER2_CERT | DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "5.3.2a",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_CORRUPT_SIGNATURE_LIST_FIRST | DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.3.2b",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_CORRUPT_SIGNATURE_LIST_FIRST | DB_STATE_SIGNER2_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "5.3.3",
    IMAGE_TYPE_MULTI_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT | DB_STATE_SIGNER2_CERT,
    DB_STATE_CORRUPT_SIGNATURE_LIST_LAST,
    EFI_ACCESS_DENIED
    ),

  TEST_SCENARIO (
    "6.1.1",
    IMAGE_TYPE_SIGNED_CORRUPT_CERT,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "6.1.2a",
    IMAGE_TYPE_SIGNED_CORRUPT_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "6.1.2b",
    IMAGE_TYPE_SIGNED_CORRUPT_CERT,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "6.2.1",
    IMAGE_TYPE_MULTI_SIGNED_CORRUPT_FIRST_CERT,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "6.3.1",
    IMAGE_TYPE_MULTI_SIGNED_CORRUPT_SECOND_CERT,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "6.3.2",
    IMAGE_TYPE_MULTI_SIGNED_CORRUPT_SECOND_CERT,
    DB_STATE_SIGNER2_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),

  TEST_SCENARIO (
    "7.1.1",
    IMAGE_TYPE_SIGNED_TAMPERED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "7.1.2",
    IMAGE_TYPE_SIGNED_TAMPERED,
    DB_STATE_SIGNER1_LEAF_TBS_HASH_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "7.1.3",
    IMAGE_TYPE_SIGNED_TAMPERED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "7.1.4",
    IMAGE_TYPE_SIGNED_TAMPERED,
    DB_STATE_EMPTY,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),

  TEST_SCENARIO (
    "8.1.1",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA1,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "8.1.2",
    IMAGE_TYPE_SIGNED,
    DB_STATE_IMAGE_DIGEST_SHA1,
    DB_STATE_EMPTY,
    EFI_ACCESS_DENIED
    ),
  TEST_SCENARIO (
    "8.2.1",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA1,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "8.2.2",
    IMAGE_TYPE_SIGNED,
    DB_STATE_SIGNER1_LEAF_CERT,
    DB_STATE_IMAGE_DIGEST_SHA1,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "8.3.1",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA1 | DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_EMPTY,
    EFI_SUCCESS
    ),
  TEST_SCENARIO (
    "8.3.2",
    IMAGE_TYPE_UNSIGNED,
    DB_STATE_IMAGE_DIGEST_SHA256,
    DB_STATE_IMAGE_DIGEST_SHA1 | DB_STATE_IMAGE_DIGEST_SHA256,
    EFI_ACCESS_DENIED
    ),
};

CONST UINTN  mScenarioCount = ARRAY_SIZE (mScenarios);
