/** @file
  Declarations for the built-in test images and signature data consumed by the Image
  Validation unit test application.

  The definitions live in the per-architecture generated files, exactly one of which is
  compiled per build (selected by the INF [Sources.<arch>] sections).

  The images are architecture-specific because a PE/COFF header declares a machine type;
  LoadImage() rejects an image whose architecture does not match the running application.
  The signer certificates are architecture-independent but are emitted into each arch file
  so each file is self-contained. The blobs are generated by GenTestData.py and checked in
  so the tests remain self-contained and deterministic.

  Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef TEST_DATA_H_
#define TEST_DATA_H_

#include <Uefi.h>

//
// Built-in PE/COFF images.
//
extern CONST UINT8  mUnsignedImage[];
extern CONST UINTN  mUnsignedImageSize;

extern CONST UINT8  mSignedImage[];
extern CONST UINTN  mSignedImageSize;

extern CONST UINT8  mMultiSignedImage[];
extern CONST UINTN  mMultiSignedImageSize;

//
// Authenticode digests of each image, one per supported hash algorithm.
//
extern CONST UINT8  mUnsignedImageDigestSha256[];
extern CONST UINTN  mUnsignedImageDigestSha256Size;

extern CONST UINT8  mUnsignedImageDigestSha384[];
extern CONST UINTN  mUnsignedImageDigestSha384Size;

extern CONST UINT8  mUnsignedImageDigestSha512[];
extern CONST UINTN  mUnsignedImageDigestSha512Size;

extern CONST UINT8  mSignedImageDigestSha256[];
extern CONST UINTN  mSignedImageDigestSha256Size;

extern CONST UINT8  mSignedImageDigestSha384[];
extern CONST UINTN  mSignedImageDigestSha384Size;

extern CONST UINT8  mSignedImageDigestSha512[];
extern CONST UINTN  mSignedImageDigestSha512Size;

extern CONST UINT8  mMultiSignedImageDigestSha256[];
extern CONST UINTN  mMultiSignedImageDigestSha256Size;

extern CONST UINT8  mMultiSignedImageDigestSha384[];
extern CONST UINTN  mMultiSignedImageDigestSha384Size;

extern CONST UINT8  mMultiSignedImageDigestSha512[];
extern CONST UINTN  mMultiSignedImageDigestSha512Size;

//
// Certificates for the signed and multi-signed images:
//
// Signer 1: The four-certificate chain for the signed image
//           (root CA -> intermediate 1 CA -> intermediate 2 CA -> leaf).
// Signer 2: The single self-signed certificate for the second signer, used for the
//           multi-signed image, plus one unrelated certificate that is embedded in signer
//           2's signature but is not part of its chain.
//
extern CONST UINT8  mLeafCert[];
extern CONST UINTN  mLeafCertSize;

extern CONST UINT8  mIntermediate1Cert[];
extern CONST UINTN  mIntermediate1CertSize;

extern CONST UINT8  mIntermediate2Cert[];
extern CONST UINTN  mIntermediate2CertSize;

extern CONST UINT8  mRootCert[];
extern CONST UINTN  mRootCertSize;

extern CONST UINT8  mSigner2Cert[];
extern CONST UINTN  mSigner2CertSize;

extern CONST UINT8  mSigner2UnrelatedCert[];
extern CONST UINTN  mSigner2UnrelatedCertSize;

#endif // TEST_DATA_H_
