jobs:
  # - job: linux_build
  #   displayName: Linux Build
  #   pool:
  #     vmImage: ubuntu-16.04

  #   workspace:
  #     clean: all

  #   steps:
  #   - checkout: self
  #     clean: true
  
  #   - task: UsePythonVersion@0
  #     inputs:
  #       versionSpec: '3.7.x'
  #       architecture: 'x64'
  #     displayName: Install correct Python

  #   - bash: sudo apt-get update
  #     displayName: Update apt

  #   - bash: sudo apt-get install gcc g++ make uuid-dev
  #     displayName: Install required tools

  #   - script: |
  #       echo '##vso[task.setvariable variable=PYTHON_COMMAND]python3'
  #     displayName: Force tools build to use new Python

  #   - bash: make -C BaseTools
  #     workingDirectory: $(Build.Repository.LocalPath)
  #     displayName: Build

  #   - task: PublishBuildArtifacts@1
  #     inputs:
  #       pathtoPublish: '$(Build.Repository.LocalPath)/BaseTools/Source/C/'
  #       artifactName: LinuxOutput

  - job: windows_build
    displayName: Windows Build
    pool:
      vmImage: vs2017-win2016

    workspace:
      clean: all

    variables:
      build_invocable: $(Build.Repository.LocalPath)\BaseTools\Edk2ToolsBuild.py

    steps:
    - checkout: self
      clean: true
  
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7.x'
        addToPath: true
        architecture: 'x64'
      displayName: Install correct Python

    - script: pip install --upgrade -r $(Build.Repository.LocalPath)\requirements.txt
      displayName: Install pip requirements

    - task: CmdLine@1
      inputs:
        filename: stuart_update
        arguments: -c $(build_invocable)
      displayName: Update invocable dependencies

    - task: PythonScript@0
      inputs:
        type: filePath
        scriptSource: $(build_invocable)
      displayName: Build

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.Repository.LocalPath)\BaseTools\Bin\Win32'
        artifactName: WindowsOutput

  # - job: assemble_package
  #   displayName: Assemble Release Package
  #   dependsOn:
  #   - linux_build
  #   - windows_build
  #   pool:
  #     vmImage: vs2017-win2016

  #   workspace:
  #     clean: all

  #   steps:
  #   - script: echo "I am here."
  #     displayName: Proof of Life
