jobs:
  - job: linux_build
    displayName: Linux Build
    pool:
      vmImage: ubuntu-16.04

    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true

  - job: windows_build
    displayName: Windows Build
    pool:
      vmImage: vs2017-win2016

    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true
