/** @file
  Implements the EDK II Crypto Protocol/PPI services using the library services
  from BaseCryptLib and TlsLib.

  Copyright (C) Microsoft Corporation. All rights reserved.
  Copyright (c) 2019 - 2020, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/
#include <Base.h>
#include <Library/DebugLib.h>
#include <Library/BaseCryptLib.h>
#include <Library/TlsLib.h>
#include <Protocol/Crypto.h>

// MU_CHANGE - Remove BaseCryptLibServiceNotEnabled and macros
//             These were added for upstreaming into EDK2 and are
//             not used by Mu. They may eventually land in EDK2, at
//             which point we will need to make a decision about
//             their inclusion here.

/**
  Returns the version of the EDK II Crypto Protocol.

  @return  The version of the EDK II Crypto Protocol.

**/
UINTN
EFIAPI
CryptoServiceGetCryptoVersion (
  VOID
  )
{
  return EDKII_CRYPTO_VERSION;
}

// MU_CHANGE [BEGIN]
// __REPLACEMENT_TAG__ - Autogenerated contents go here.
// MU_CHANGE [END]
