variables:
  linux_build_output_path: '$(Build.Repository.LocalPath)/BaseTools/Source/C/bin'
  linux_artifact_name: 'LinuxOutput'
  windows_build_output_path: '$(Build.Repository.LocalPath)\BaseTools\Bin\Win32'
  windows_artifact_name: 'WindowsOutput'
  temp_publication_directory: 'PackageStaging'

jobs:
  - job: linux_build
    displayName: Linux Build
    pool:
      vmImage: ubuntu-latest

    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true
  
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7.x'
        architecture: 'x64'
      displayName: Install correct Python

    - script: pip install -r requirements.txt --upgrade
      displayName: 'Install/Upgrade pip modules'

    # Set default
    - bash: |
        echo "##vso[task.setvariable variable=pkg_count]${{ 1 }}"

    - task: CmdLine@1
      displayName: Update Environment
      inputs:
        filename: stuart_update
        arguments: -c .pytool/CISettings.py

    - template: templates/basetools-build-steps.yml
      parameters:
        tool_chain_tag: 'GCC5'

    - powershell: Get-ChildItem -Recurse -Include "*_path_env.yaml", "*_path_env.yml" -Path $(linux_build_output_path) | Remove-Item
      displayName: Remove Unnecessary Files

    - publish: $(linux_build_output_path)
      artifact: $(linux_artifact_name)
      displayName: Publish To Pipeline

  # - job: windows_build
  #   displayName: Windows Build
  #   pool:
  #     vmImage: windows-latest

  #   workspace:
  #     clean: all

  #   steps:
  #   - checkout: self
  #     clean: true
  
  #   - task: UsePythonVersion@0
  #     inputs:
  #       versionSpec: '3.7.x'
  #       addToPath: true
  #       architecture: 'x64'
  #     displayName: Install correct Python

  #   - script: pip install -r requirements.txt --upgrade
  #     displayName: 'Install/Upgrade pip modules'

  #   # Set default
  #   - bash: |
  #       echo "##vso[task.setvariable variable=pkg_count]${{ 1 }}"

  #   - task: CmdLine@1
  #     displayName: Update Environment
  #     inputs:
  #       filename: stuart_update
  #       arguments: -c .pytool/CISettings.py

  #   - template: templates/basetools-build-steps.yml
  #     parameters:
  #       tool_chain_tag: 'VS2019'

  #   - task: PublishBuildArtifacts@1
  #     inputs:
  #       pathtoPublish: $(windows_build_output_path)
  #       artifactName: $(windows_artifact_name)

  - job: assemble_package
    displayName: Assemble Release Package
    dependsOn:
    - linux_build
    # - windows_build
    pool:
      vmImage: windows-latest

    workspace:
      clean: all

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7.x'
        addToPath: true
        architecture: 'x64'
      displayName: Install correct Python

    - script: pip install edk2-pytool-library==0.10.* edk2-pytool-extensions==0.12.*
      displayName: 'Install/Upgrade pip modules'

    - download: current
      artifact: $(linux_artifact_name), $(windows_artifact_name)

    - powershell:
        mkdir $(Build.StagingDirectory)/$(temp_publication_directory);
        mv $(Pipeline.Workspace)/$(linux_artifact_name) $(Build.StagingDirectory)/$(temp_publication_directory)/Linux-x86;
        mv $(Pipeline.Workspace)/$(windows_artifact_name) $(Build.StagingDirectory)/$(temp_publication_directory)/Windows-x86;
      displayName: 'Info about stuff'
