jobs:
  - job: linux_build
    displayName: Linux Build
    pool:
      vmImage: ubuntu-latest

    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true
  
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7.x'
        architecture: 'x64'
      displayName: Install correct Python

    - script: pip install -r requirements.txt --upgrade
      displayName: 'Install/Upgrade pip modules'

    - task: CmdLine@1
      displayName: Update Environment
      inputs:
        filename: stuart_update
        arguments: -c .pytool/CISettings.py

    - template: templates/basetools-build-steps.yml
      parameters:
        tool_chain_tag: 'GCC5'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.Repository.LocalPath)/BaseTools/Source/C/bin'
        artifactName: LinuxOutput

  - job: windows_build
    displayName: Windows Build
    pool:
      vmImage: vs2017-win2016

    workspace:
      clean: all

    variables:
      build_invocable: $(Build.Repository.LocalPath)\BaseTools\Edk2ToolsBuild.py

    steps:
    - checkout: self
      clean: true
  
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7.x'
        addToPath: true
        architecture: 'x64'
      displayName: Install correct Python

    - script: pip install -r requirements.txt --upgrade
      displayName: 'Install/Upgrade pip modules'

    - task: CmdLine@1
      displayName: Update Environment
      inputs:
        filename: stuart_update
        arguments: -c .pytool/CISettings.py

    - template: templates/basetools-build-steps.yml
      parameters:
        tool_chain_tag: 'VS2019'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.Repository.LocalPath)\BaseTools\Bin\Win32'
        artifactName: WindowsOutput

  # - job: assemble_package
  #   displayName: Assemble Release Package
  #   dependsOn:
  #   - linux_build
  #   - windows_build
  #   pool:
  #     vmImage: vs2017-win2016

  #   workspace:
  #     clean: all

  #   steps:
  #   - script: echo "I am here."
  #     displayName: Proof of Life
