## @file
# Template file for generating a build job matrix for the packages currently supported for
# build in Mu Basecore.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
- name: arch_list
  displayName: Architectures (e.g. IA32, X64)
  type: string
  default: ''
- name: extra_build_args
  displayName: Extra Build Command Arguments
  type: string
  default: ''
- name: extra_install_step
  displayName: Extra Install Steps
  type: stepList
  default:
    - script: echo No extra steps provided
- name: tool_chain_tag
  displayName: Tool Chain (e.g. VS2022)
  type: string
  default: ''
- name: vm_image
  displayName: Virtual Machine Image (e.g. windows-latest)
  type: string
  default: 'windows-latest'

jobs:

- job: Build
  timeoutInMinutes: 120
  # Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_MDE_CPU:
        Build.Pkgs: 'MdePkg,UefiCpuPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_MDEMODULE_DEBUG:
        Build.Pkgs: 'MdeModulePkg'
        Build.Targets: 'DEBUG,NOOPT'
      TARGET_MDEMODULE_RELEASE:
        Build.Pkgs: 'MdeModulePkg'
        Build.Targets: 'RELEASE,NO-TARGET'
      TARGET_NETWORK:
        Build.Pkgs: 'NetworkPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_OTHER:
        Build.Pkgs: 'PcAtChipsetPkg,ShellPkg,StandaloneMmPkg,BaseTools'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_TEST_POLICY:
        Build.Pkgs: 'UnitTestFrameworkPkg,PolicyServicePkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_CRYPTO:
        Build.Pkgs: 'CryptoPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'

  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - template: Steps/PrGate.yml@mu_devops
    parameters:
      build_archs: ${{ parameters.arch_list }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      do_ci_build: true
      do_ci_setup: false
      do_non_ci_build: false
      do_non_ci_setup: true
      do_pr_eval: true
      extra_build_args: ${{ parameters.extra_build_args }}
      extra_install_step: ${{ parameters.extra_install_step }}
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
