## @file
# Azure Pipeline build file for a build using mu_devops.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

{% import '../../../Version.njk' as sync_version -%}

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/{{ sync_version.mu_devops }}

parameters:
- name: do_ci_build
  displayName: Perform Stuart CI Build
  type: boolean
  default: true
- name: do_ci_setup
  displayName: Perform Stuart CI Setup
  type: boolean
  default: true
- name: do_non_ci_build
  displayName: Perform non-CI Stuart Build
  type: boolean
  default: false
- name: do_non_ci_setup
  displayName: Perform non-CI Stuart Setup
  type: boolean
  default: false
- name: do_pr_eval
  displayName: Perform Stuart PR Evaluation
  type: boolean
  default: true
- name: container_build
  displayName: Flag for whether this repo should do stuart_setup
  type: boolean
  default: false
- name: os_type
  displayName: OS type on the self-hosted agent pools
  type: string
  values:
  - Windows_NT
  - Linux
  default: Windows_NT
- name: build_matrix
  displayName: Build matrix for this repository
  type: object
- name: pool_name
  displayName: Variable name that hosts pool name to be used for self-hosted agents
  type: string
  default: pool_name
- name: extra_install_step
  displayName: Extra Install Steps
  type: stepList
  default:
    - script: echo No extra steps provided
- name: extra_jobs
  displayName: Extra Jobs to be run after build
  type: jobList
  default: []

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    do_ci_build: ${{ parameters.do_ci_build }}
    do_ci_setup: ${{ parameters.do_ci_setup }}
    do_pr_eval: ${{ parameters.do_pr_eval }}
    do_non_ci_setup: ${{ parameters.do_non_ci_setup }}
    do_non_ci_build: ${{ parameters.do_non_ci_build }}
    build_matrix: ${{ parameters.build_matrix }}
    os_type: ${{ parameters.os_type }}
    pool_name: ${{ parameters.pool_name }}
    extra_install_step: ${{ parameters.extra_install_step }}
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
    container_build: ${{ parameters.container_build }}
    linux_container_image: {{ sync_version.linux_build_container }}

- ${{ parameters.extra_jobs }}
