## @file
# Azure Pipeline build file for a build using Ubuntu and CLANGPDB.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: architectures-x86-64
- group: tool-chain-clangpdb
- group: tool-chain-clangpdb-windows-vm-image

jobs:
- template: templates/matrix-build-job-clang.yml
  parameters:
    arch_list: $(arch_list)
    extra_steps:
      - script: sudo apt-get install mingw-w64
        displayName: Install Windows Resource Compiler for Linux
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
