## @file
# Azure Pipeline build file for a build using Ubuntu and GCC.
#
# IMPORTANT: This file requires the local repo to contain a .azurepipelines/Matrix-Build-Job.yml file that
#            performs the actual build steps for the configurations and packages supported by the repo.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: architectures-arm-64-x86-64
- group: tool-chain-ubuntu-gcc

jobs:
- template: Matrix-Build-Job.yml
  parameters:
    arch_list: $(arch_list)
    extra_build_args: CODE_COVERAGE=TRUE CC_HTML=TRUE
    extra_install_step:
    - script: |
              sudo apt-get install -y mingw-w64 lcov
              pip install lcov_cobertura pycobertura
      displayName: Install Windows Resource Compiler for Linux & Code Coverage Tools
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
