## @file
# Azure Pipeline build file for a build using Windows and VS2022
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
# MU_CHANGE [BEGIN]
trigger:
- dev/*
- release/*

schedules:
- cron: "0 8 * * 0,3"   # Sun/Wed at 1AM Pacific
  displayName: Sun/Wed Build
  branches:
    include:
    - dev/*
    - release/*
  always: true          # Always build, even if no changes

pr:
- dev/*
- release/*
# MU_CHANGE [END]

variables:
  - template: templates/defaults.yml

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2022'
    vm_image: 'windows-2022'
    arch_list: "IA32,X64"
    usePythonVersion: ${{ variables.default_python_version }}
    extra_install_step:
    - powershell: choco install opencppcoverage; Write-Host "##vso[task.prependpath]C:\Program Files\OpenCppCoverage"
      displayName: Install Code Coverage Tool
      condition: and(gt(variables.pkg_count, 0), succeeded())

