## @file
# Azure Pipeline build file for a build using Windows and CLANGPDB.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: architectures-x86-64
- group: tool-chain-clangpdb
- group: tool-chain-clangpdb-ubuntu-vm-image

jobs:
- template: Matrix-Build-Job-Clang.yml
  parameters:
    arch_list: $(arch_list)
    extra_install_step:
      - powershell: choco install llvm
        displayName: Install LLVM and CLANG
        condition: and(gt(variables.pkg_count, 0), succeeded())
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
