## @file
# GNU/Linux makefile for 'GenStm' module build.
#
# Copyright (c) 2009 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# MU_CHANGE [WHOLE FILE] - Add the GenStm application
#
#
MAKEROOT ?= ..

APPNAME = GenStm

LIBS = -lCommon

OBJECTS = GenStm.o

include $(MAKEROOT)/Makefiles/app.makefile
