## @file
# Windows makefile for the GenStm C tool build.
#
# Copyright (c) 2009 - 2018, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# MU_CHANGE [WHOLE FILE] - Add the GenStm application

!INCLUDE $(BASE_TOOLS_PATH)\Source\C\Makefiles\ms.common

APPNAME = GenStm

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = GenStm.obj

!INCLUDE $(BASE_TOOLS_PATH)\Source\C\Makefiles\ms.app
