# This workflow automatically publishes the basetools binaries for a given
# release.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: BaseTools Build

on:
  release:
    types:
      - published
  pull_request:
    branches:
      - release/**
    paths:
      - ".github/workflows/release-basetools.yml"
      - "BaseTools/**"

jobs:
  build:
    name: Build Base Tools
    strategy:
      matrix:
        include:
          - os: windows-2022
            tool_chain: VS2022
            output_dir: "BaseTools\\Bin\\Win32"
            target: IA32

          - os: windows-2022
            tool_chain: VS2022
            output_dir: "BaseTools\\Bin\\Win64"
            target: AARCH64

          - os: ubuntu-22.04
            tool_chain: GCC5
            output_dir: "BaseTools/Source/C/bin"
            target: X64

          - os: ubuntu-22.04
            tool_chain: GCC5
            output_dir: "BaseTools/Source/C/bin"
            target: AARCH64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linux Tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi g++-aarch64-linux-gnu g++-arm-linux-gnueabi
          echo "GCC5_AARCH64_PREFIX=/usr/bin/aarch64-linux-gnu-" >> "$GITHUB_ENV"
          echo "GCC5_ARM_PREFIX=/usr/bin/arm-linux-gnueabi-" >> "$GITHUB_ENV"

      - name: Install Pip Modules
        run: pip install -r pip-requirements.txt --upgrade

      - name: Stuart Setup
        run: stuart_setup -c .pytool/CISettings.py

      - name: Stuart Update
        run: stuart_update -c .pytool/CISettings.py TOOL_CHAIN_TAG=${{ matrix.tool_chain}} -a ${{ matrix.target }}

      - name: Build Base Tools
        run: python BaseTools/Edk2ToolsBuild.py -t ${{ matrix.tool_chain}} -a ${{ matrix.target }} --skip_path_env

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.tool_chain }}-${{ matrix.target }}
          path: |
            Build/SETUPLOG.txt
            Build/UPDATE_LOG.txt
            BaseTools/BaseToolsBuild/BASETOOLS_BUILD.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: basetools-${{ matrix.tool_chain }}-${{ matrix.target }}
          path: ${{ matrix.output_dir }}

  publish:
    name: Publish Base Tools
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    env:
      ARTIFACT_BASE_URL: https://github.com/microsoft/mu_basecore/releases/download
      BASETOOLS_PATH: BaseTools/Bin/basetoolsbin_ext_dep.yaml

    permissions:
      contents: write

    steps:
      - name: Determine Branch
        shell: bash
        id: branch
        run: |
          # Example: dev-v2025020000.0.2
          RELEASE_NAME="${{ github.event.release.tag_name }}"
          URL_PREFIX="${{ env.ARTIFACT_BASE_URL }}"
          
          echo "Release tag name: ${RELEASE_NAME}"

          # release builds do not have "release" in their tag name
          if [[ ${RELEASE_NAME} == release* ]]; then
            echo "Detected release branch."
            IS_RELEASE=true
          else
            IS_RELEASE=false
          fi

          DATE=$(echo "$RELEASE_NAME" | sed -E 's/.*-v([0-9]{6}).*/\1/')

          if [[ ${IS_RELEASE} == true ]]; then
            BRANCH_NAME="release/${DATE}"
          else
            BRANCH_NAME="dev/${DATE}"
          fi

          echo "Branch name: ${BRANCH_NAME}"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

          SOURCE_URL=${URL_PREFIX}/${RELEASE_NAME}/basetools-${RELEASE_NAME}.tar.gz
          echo "Release URL: ${SOURCE_URL}"
          echo "source_url=${SOURCE_URL}" >> $GITHUB_OUTPUT

          VERSION=${RELEASE_NAME}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.branch_name }}

      - name: Download Dependencies
        shell: bash
        run: sudo apt install jq moreutils -y

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/artifacts

      - name: Stage Files
        run: mkdir ${{ runner.temp }}/basetools ;
          mv ${{ runner.temp }}/artifacts/basetools-GCC5-X64       ${{ runner.temp }}/basetools/Linux-x86 ;
          chmod a+x ${{ runner.temp }}/basetools/Linux-x86/* ;
          mv ${{ runner.temp }}/artifacts/basetools-GCC5-AARCH64   ${{ runner.temp }}/basetools/Linux-ARM-64 ;
          chmod a+x ${{ runner.temp }}/basetools/Linux-ARM-64/* ;
          mv ${{ runner.temp }}/artifacts/basetools-VS2022-IA32    ${{ runner.temp }}/basetools/Windows-x86 ;
          mv ${{ runner.temp }}/artifacts/basetools-VS2022-AARCH64 ${{ runner.temp }}/basetools/Windows-ARM-64 ;

      - name: Package Files
        run: |
          cd ${{ runner.temp }} ;
          zip -r basetools-${{ github.event.release.tag_name }}.zip basetools/* ;
          tar -czf basetools-${{ github.event.release.tag_name }}.tar.gz basetools/*

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ runner.temp }}/basetools-*.zip
          gh release upload ${{ github.event.release.tag_name }} ${{ runner.temp }}/basetools-*.tar.gz

      - name: Update BaseTools External Dependency File
        shell: bash
        run: |
          PATH="${{ env.BASETOOLS_PATH }}"
          SOURCE="${{ steps.branch.outputs.source_url }}"
          VERSION="${{ steps.branch.outputs.version }}"
          SHA256=$(curl -sSL "${SOURCE}" | sha256sum | awk '{print $1}')
          
          jq '.source = "${SOURCE}" | .version = "${VERSION}" | .sha256 = "${SHA256}"' ${PATH} | sponge ${PATH}
      
      - name: Commit Change and push
        shell: bash
        run: |
          git config user.name "uefibot"
          git config user.email "uefibot@microsoft.com"
          git add .
          git commit -m "Update BaseTools ext dep to ${{ steps.branch.outputs.version }}" -m "" -m "Signed-off-by: Project Mu UEFI Bot <uefibot@microsoft.com>"
          git push origin HEAD:refs/heads/sync-basetools/${{ github.event.release.tag_name }}
